### ISSUE TITLE
Fin io should support @base: for relative paths

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/fin#22]
To get around the inconsistencies of relative paths when creating containers in fcrepo, `fin io` should support a `@base:` prefix.

Example:

Filesystem:
- foo.jsonld.json
- foo 
  - bar.jsonld.json
  - bar
    - myimage.png

bar.jsonld.json 
```json
{
  "image" : "@base:myimage.png"
}
```
When bar.jsonld.json is post'd to `http://example.org/item/foo/bar`, fin io will replace update all instances of `@base:` with `http://example.org/item/foo/bar`. So bar.jsonld.json will become:

```json
{
  "image" : "http://example.org/item/foo/bar/myimage.png"
}
```

Additionally using `@base` would let users read the jsonld files adding a `@base` to the `@context` and standard jsonld parsers should work.

**Comment by qjhart** [comment]
This is how I'm thinking of it: 

Fin IO will set / or overwrite the `@base` context directive to the fcrepo destination location.  Fin will send expand all relative paths to explicit paths before uploading  to fcrepo.

As an Example, users can imagine that this: 

```json 
{ 
   "@context": [
     "http://schema.org/",
            {
             "ucdrp":"http://schema.library/ucdavis.edu/",
             "local_thing": { "@id":"ucdrp:local_thing",
                                        "@type":"@id" }
           },
],
  "@id":"",
   "local_thing":"media/example.png"
}
 ```

Looks as if it were, if FIN decided this file needed to go to `info:fedora/ark:/99/pets`
See [playground](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%5B%22http%3A%2F%2Fschema.org%2F%22%2C%7B%22ucdrp%22%3A%22http%3A%2F%2Fschema.library%2Fucdavis.edu%2F%22%2C%22local_thing%22%3A%7B%22%40id%22%3A%22ucdrp%3Alocal_thing%22%2C%22%40type%22%3A%22%40id%22%7D%7D%2C%7B%22%40base%22%3A%22http%3A%2F%2Flocalhost%3A8080%2Ffcrepo%2Frest%2Fark%3A%2F99%2Fpets%22%7D%5D%2C%22%40id%22%3A%22%40base%3A%22%2C%22local_thing%22%3A%22media%2Fexample.png%22%7D)

```json
{ 
   "@context": [
     "http://schema.org/",
            {
             "ucdrp":"http://schema.library/ucdavis.edu/",
             "local_thing": { "@id":"ucdrp:local_thing",
                                        "@type":"@id" }
           },
     {"@base":"http://localhost:8080/fcrepo/rest/ark:/99/pets"}
],
  "@id":"@base:",
   "local_thing":"media/example.png"
}
 ```

User's can explicitily add `@base:` if they'd like to make clear the path for the object.
