### ISSUE TITLE
gcssync is not being properly initialized

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/fin#31]
This is causing the following error: 

```
[ActiveMQ VMTransport: vm://localhost#1-2] (Queue) Usage Manager Memory Limit (1048576) reached on queue://gcssync, size 30539. Producers will be throttled to the rate at which messages are removed from this destination to prevent flooding it. See http://activemq.apache.org/producer-flow-control.html for more info.
```

A note on this, users, when extending fin, need to be sure an remove the gcssync queue if they are not using it in the activemq.xml file.  @qjhart should be just make this a required addition if you want to opt in to gcssync (rather than opt out)?

**Comment by qjhart** [comment]
By opt out you just mean write my own activemq.xml file?  If that's the case, I would say opting *out* is better, since workflows should be a normal part of the landscape ?

**Comment by jrmerz** [comment]
`gcssync` is not part of the `fin workflows` feature.

Currently the fin default activemq.xml file defines two queues, `/queue/dbsync` and `/queue/gcssync`.  If a user doesn't not include the `gcs service` or does not override the default activemq.xml file, the `/queue/gcssync` queue will fill up.  ActiveMQ does not remove messages in queues (unless a ttl is set).  If the `/queue/gcssync` activemq queue fills up (ex: you don't include the `gcs service` in your application to read and ack the messages), ActiveMQ stops adding messages to any queue, this includes `/queue/dbsync`, which effectively breaks fin.
