### ISSUE TITLE
Add link from validation to dbsync

### ISSUE THREAD

**Issue by qjhart** [ucd-library/fin#86]
The validation page organized issues well, but they are more actionable on the dbsync page.  Include a link between them, maybe something like: 

![image](https://github.com/user-attachments/assets/4a3ebad4-d3a6-4259-b68d-fd617afba396)

Which goes to: 

![image](https://github.com/user-attachments/assets/e3eacdc6-1d6e-46e0-94f3-65f951363a8d)

**Comment by jrmerz** [comment]
Ya, technically there is no relationship between the fcrepo id and the database id.  We just use the same path/id's in the DAMS, and I think AE.  So as far as fin is concerned, there is no reason a database id exists as a path in fcrepo.
