### ISSUE TITLE
Allow Reindex (and workflows?) from the validation page

### ISSUE THREAD

**Issue by qjhart** [ucd-library/fin#87]
Often, you'd like to run a reindex or common workflow on a number of items with  the same error or warning, Perhaps allow these directly on the validation page? 

![image](https://github.com/user-attachments/assets/7e5cfa08-a67d-4e80-a092-96ce1abd22b6)

**Comment by jrmerz** [comment]
See comment on https://github.com/ucd-library/fin/issues/86 about showing reindex on this page.  Workflows can currently be reindex in bulk by using CLI.
